//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bindings_demo_service_client.CalculatorServiceV2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://itstep.org/CalculatorSerice/V2", ConfigurationName="CalculatorServiceV2.ICalculatorService2")]
    public interface ICalculatorService2 {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://itstep.org/CalculatorSerice/V1) of message GetPythonsRequest does not match the default value (http://itstep.org/CalculatorSerice/V2)
        [System.ServiceModel.OperationContractAttribute(Action="http://itstep.org/CalculatorSerice/V1/ICalculatorService/GetPythons", ReplyAction="http://itstep.org/CalculatorSerice/V1/ICalculatorService/GetPythonsResponse")]
        bindings_demo_service_client.CalculatorServiceV2.GetPythonsResponse GetPythons(bindings_demo_service_client.CalculatorServiceV2.GetPythonsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://itstep.org/CalculatorSerice/V1/ICalculatorService/GetPythons", ReplyAction="http://itstep.org/CalculatorSerice/V1/ICalculatorService/GetPythonsResponse")]
        System.Threading.Tasks.Task<bindings_demo_service_client.CalculatorServiceV2.GetPythonsResponse> GetPythonsAsync(bindings_demo_service_client.CalculatorServiceV2.GetPythonsRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://itstep.org/CalculatorSerice/V1) of message GetParrotsRequest does not match the default value (http://itstep.org/CalculatorSerice/V2)
        [System.ServiceModel.OperationContractAttribute(Action="http://itstep.org/CalculatorSerice/V1/ICalculatorService/GetParrots", ReplyAction="http://itstep.org/CalculatorSerice/V1/ICalculatorService/GetParrotsResponse")]
        bindings_demo_service_client.CalculatorServiceV2.GetParrotsResponse GetParrots(bindings_demo_service_client.CalculatorServiceV2.GetParrotsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://itstep.org/CalculatorSerice/V1/ICalculatorService/GetParrots", ReplyAction="http://itstep.org/CalculatorSerice/V1/ICalculatorService/GetParrotsResponse")]
        System.Threading.Tasks.Task<bindings_demo_service_client.CalculatorServiceV2.GetParrotsResponse> GetParrotsAsync(bindings_demo_service_client.CalculatorServiceV2.GetParrotsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://itstep.org/CalculatorSerice/V2/ICalculatorService2/GetFloatingPointPythons" +
            "", ReplyAction="http://itstep.org/CalculatorSerice/V2/ICalculatorService2/GetFloatingPointPythons" +
            "Response")]
        double GetFloatingPointPythons(double parrotsCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://itstep.org/CalculatorSerice/V2/ICalculatorService2/GetFloatingPointPythons" +
            "", ReplyAction="http://itstep.org/CalculatorSerice/V2/ICalculatorService2/GetFloatingPointPythons" +
            "Response")]
        System.Threading.Tasks.Task<double> GetFloatingPointPythonsAsync(double parrotsCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://itstep.org/CalculatorSerice/V2/ICalculatorService2/GetFloatingPointParrots" +
            "", ReplyAction="http://itstep.org/CalculatorSerice/V2/ICalculatorService2/GetFloatingPointParrots" +
            "Response")]
        double GetFloatingPointParrots(double pythonsCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://itstep.org/CalculatorSerice/V2/ICalculatorService2/GetFloatingPointParrots" +
            "", ReplyAction="http://itstep.org/CalculatorSerice/V2/ICalculatorService2/GetFloatingPointParrots" +
            "Response")]
        System.Threading.Tasks.Task<double> GetFloatingPointParrotsAsync(double pythonsCount);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPythons", WrapperNamespace="http://itstep.org/CalculatorSerice/V1", IsWrapped=true)]
    public partial class GetPythonsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://itstep.org/CalculatorSerice/V1", Order=0)]
        public int parrotsCount;
        
        public GetPythonsRequest() {
        }
        
        public GetPythonsRequest(int parrotsCount) {
            this.parrotsCount = parrotsCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPythonsResponse", WrapperNamespace="http://itstep.org/CalculatorSerice/V1", IsWrapped=true)]
    public partial class GetPythonsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://itstep.org/CalculatorSerice/V1", Order=0)]
        public int GetPythonsResult;
        
        public GetPythonsResponse() {
        }
        
        public GetPythonsResponse(int GetPythonsResult) {
            this.GetPythonsResult = GetPythonsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetParrots", WrapperNamespace="http://itstep.org/CalculatorSerice/V1", IsWrapped=true)]
    public partial class GetParrotsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://itstep.org/CalculatorSerice/V1", Order=0)]
        public int pythonsCount;
        
        public GetParrotsRequest() {
        }
        
        public GetParrotsRequest(int pythonsCount) {
            this.pythonsCount = pythonsCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetParrotsResponse", WrapperNamespace="http://itstep.org/CalculatorSerice/V1", IsWrapped=true)]
    public partial class GetParrotsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://itstep.org/CalculatorSerice/V1", Order=0)]
        public int GetParrotsResult;
        
        public GetParrotsResponse() {
        }
        
        public GetParrotsResponse(int GetParrotsResult) {
            this.GetParrotsResult = GetParrotsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalculatorService2Channel : bindings_demo_service_client.CalculatorServiceV2.ICalculatorService2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorService2Client : System.ServiceModel.ClientBase<bindings_demo_service_client.CalculatorServiceV2.ICalculatorService2>, bindings_demo_service_client.CalculatorServiceV2.ICalculatorService2 {
        
        public CalculatorService2Client() {
        }
        
        public CalculatorService2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatorService2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorService2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorService2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bindings_demo_service_client.CalculatorServiceV2.GetPythonsResponse bindings_demo_service_client.CalculatorServiceV2.ICalculatorService2.GetPythons(bindings_demo_service_client.CalculatorServiceV2.GetPythonsRequest request) {
            return base.Channel.GetPythons(request);
        }
        
        public int GetPythons(int parrotsCount) {
            bindings_demo_service_client.CalculatorServiceV2.GetPythonsRequest inValue = new bindings_demo_service_client.CalculatorServiceV2.GetPythonsRequest();
            inValue.parrotsCount = parrotsCount;
            bindings_demo_service_client.CalculatorServiceV2.GetPythonsResponse retVal = ((bindings_demo_service_client.CalculatorServiceV2.ICalculatorService2)(this)).GetPythons(inValue);
            return retVal.GetPythonsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bindings_demo_service_client.CalculatorServiceV2.GetPythonsResponse> bindings_demo_service_client.CalculatorServiceV2.ICalculatorService2.GetPythonsAsync(bindings_demo_service_client.CalculatorServiceV2.GetPythonsRequest request) {
            return base.Channel.GetPythonsAsync(request);
        }
        
        public System.Threading.Tasks.Task<bindings_demo_service_client.CalculatorServiceV2.GetPythonsResponse> GetPythonsAsync(int parrotsCount) {
            bindings_demo_service_client.CalculatorServiceV2.GetPythonsRequest inValue = new bindings_demo_service_client.CalculatorServiceV2.GetPythonsRequest();
            inValue.parrotsCount = parrotsCount;
            return ((bindings_demo_service_client.CalculatorServiceV2.ICalculatorService2)(this)).GetPythonsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bindings_demo_service_client.CalculatorServiceV2.GetParrotsResponse bindings_demo_service_client.CalculatorServiceV2.ICalculatorService2.GetParrots(bindings_demo_service_client.CalculatorServiceV2.GetParrotsRequest request) {
            return base.Channel.GetParrots(request);
        }
        
        public int GetParrots(int pythonsCount) {
            bindings_demo_service_client.CalculatorServiceV2.GetParrotsRequest inValue = new bindings_demo_service_client.CalculatorServiceV2.GetParrotsRequest();
            inValue.pythonsCount = pythonsCount;
            bindings_demo_service_client.CalculatorServiceV2.GetParrotsResponse retVal = ((bindings_demo_service_client.CalculatorServiceV2.ICalculatorService2)(this)).GetParrots(inValue);
            return retVal.GetParrotsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bindings_demo_service_client.CalculatorServiceV2.GetParrotsResponse> bindings_demo_service_client.CalculatorServiceV2.ICalculatorService2.GetParrotsAsync(bindings_demo_service_client.CalculatorServiceV2.GetParrotsRequest request) {
            return base.Channel.GetParrotsAsync(request);
        }
        
        public System.Threading.Tasks.Task<bindings_demo_service_client.CalculatorServiceV2.GetParrotsResponse> GetParrotsAsync(int pythonsCount) {
            bindings_demo_service_client.CalculatorServiceV2.GetParrotsRequest inValue = new bindings_demo_service_client.CalculatorServiceV2.GetParrotsRequest();
            inValue.pythonsCount = pythonsCount;
            return ((bindings_demo_service_client.CalculatorServiceV2.ICalculatorService2)(this)).GetParrotsAsync(inValue);
        }
        
        public double GetFloatingPointPythons(double parrotsCount) {
            return base.Channel.GetFloatingPointPythons(parrotsCount);
        }
        
        public System.Threading.Tasks.Task<double> GetFloatingPointPythonsAsync(double parrotsCount) {
            return base.Channel.GetFloatingPointPythonsAsync(parrotsCount);
        }
        
        public double GetFloatingPointParrots(double pythonsCount) {
            return base.Channel.GetFloatingPointParrots(pythonsCount);
        }
        
        public System.Threading.Tasks.Task<double> GetFloatingPointParrotsAsync(double pythonsCount) {
            return base.Channel.GetFloatingPointParrotsAsync(pythonsCount);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://itstep.org/CalculatorSerice/V1", ConfigurationName="CalculatorServiceV2.ICalculatorService")]
    public interface ICalculatorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://itstep.org/CalculatorSerice/V1/ICalculatorService/GetPythons", ReplyAction="http://itstep.org/CalculatorSerice/V1/ICalculatorService/GetPythonsResponse")]
        int GetPythons(int parrotsCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://itstep.org/CalculatorSerice/V1/ICalculatorService/GetPythons", ReplyAction="http://itstep.org/CalculatorSerice/V1/ICalculatorService/GetPythonsResponse")]
        System.Threading.Tasks.Task<int> GetPythonsAsync(int parrotsCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://itstep.org/CalculatorSerice/V1/ICalculatorService/GetParrots", ReplyAction="http://itstep.org/CalculatorSerice/V1/ICalculatorService/GetParrotsResponse")]
        int GetParrots(int pythonsCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://itstep.org/CalculatorSerice/V1/ICalculatorService/GetParrots", ReplyAction="http://itstep.org/CalculatorSerice/V1/ICalculatorService/GetParrotsResponse")]
        System.Threading.Tasks.Task<int> GetParrotsAsync(int pythonsCount);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalculatorServiceChannel : bindings_demo_service_client.CalculatorServiceV2.ICalculatorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorServiceClient : System.ServiceModel.ClientBase<bindings_demo_service_client.CalculatorServiceV2.ICalculatorService>, bindings_demo_service_client.CalculatorServiceV2.ICalculatorService {
        
        public CalculatorServiceClient() {
        }
        
        public CalculatorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetPythons(int parrotsCount) {
            return base.Channel.GetPythons(parrotsCount);
        }
        
        public System.Threading.Tasks.Task<int> GetPythonsAsync(int parrotsCount) {
            return base.Channel.GetPythonsAsync(parrotsCount);
        }
        
        public int GetParrots(int pythonsCount) {
            return base.Channel.GetParrots(pythonsCount);
        }
        
        public System.Threading.Tasks.Task<int> GetParrotsAsync(int pythonsCount) {
            return base.Channel.GetParrotsAsync(pythonsCount);
        }
    }
}
