//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace calculator_service_client.CalculatorServiceV1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://itstep.org/CalculatorSerice/V1", ConfigurationName="CalculatorServiceV1.ICalculatorService")]
    public interface ICalculatorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://itstep.org/CalculatorSerice/V1/ICalculatorService/GetPythons", ReplyAction="http://itstep.org/CalculatorSerice/V1/ICalculatorService/GetPythonsResponse")]
        int GetPythons(int parrotsCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://itstep.org/CalculatorSerice/V1/ICalculatorService/GetPythons", ReplyAction="http://itstep.org/CalculatorSerice/V1/ICalculatorService/GetPythonsResponse")]
        System.Threading.Tasks.Task<int> GetPythonsAsync(int parrotsCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://itstep.org/CalculatorSerice/V1/ICalculatorService/GetParrots", ReplyAction="http://itstep.org/CalculatorSerice/V1/ICalculatorService/GetParrotsResponse")]
        int GetParrots(int pythonsCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://itstep.org/CalculatorSerice/V1/ICalculatorService/GetParrots", ReplyAction="http://itstep.org/CalculatorSerice/V1/ICalculatorService/GetParrotsResponse")]
        System.Threading.Tasks.Task<int> GetParrotsAsync(int pythonsCount);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalculatorServiceChannel : calculator_service_client.CalculatorServiceV1.ICalculatorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorServiceClient : System.ServiceModel.ClientBase<calculator_service_client.CalculatorServiceV1.ICalculatorService>, calculator_service_client.CalculatorServiceV1.ICalculatorService {
        
        public CalculatorServiceClient() {
        }
        
        public CalculatorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetPythons(int parrotsCount) {
            return base.Channel.GetPythons(parrotsCount);
        }
        
        public System.Threading.Tasks.Task<int> GetPythonsAsync(int parrotsCount) {
            return base.Channel.GetPythonsAsync(parrotsCount);
        }
        
        public int GetParrots(int pythonsCount) {
            return base.Channel.GetParrots(pythonsCount);
        }
        
        public System.Threading.Tasks.Task<int> GetParrotsAsync(int pythonsCount) {
            return base.Channel.GetParrotsAsync(pythonsCount);
        }
    }
}
