//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tickets.entityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Descriptions
    {
        public Descriptions()
        {
            this.Movies = new HashSet<Movies>();
        }
    
        public int Id { get; set; }
        public string AboutShow { get; set; }
        public string Actors { get; set; }
        public string Produsers { get; set; }
        public int DurationInMinutes { get; set; }
        public string Scenary { get; set; }
        public string Genres { get; set; }
    
        public virtual ICollection<Movies> Movies { get; set; }
    }
}
