//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tickets.entityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movies
    {
        public Movies()
        {
            this.PerformanceDays = new HashSet<PerformanceDays>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public int DescriptionId { get; set; }
        public string CinemaHallName { get; set; }
    
        public virtual Descriptions Descriptions { get; set; }
        public virtual ICollection<PerformanceDays> PerformanceDays { get; set; }
    }
}
