//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class Description
    {
        public Description()
        {
            this.DescriptionGenres = new HashSet<DescriptionGenres>();
            this.Shows = new HashSet<Shows>();
        }
    
        public int Id { get; set; }
        public string AboutShow { get; set; }
        public string Actors { get; set; }
        public string Produsers { get; set; }
        public int DurationInMinutes { get; set; }
        public string Scenery { get; set; }
    
        public virtual ICollection<DescriptionGenres> DescriptionGenres { get; set; }
        public virtual ICollection<Shows> Shows { get; set; }
    }
}
