//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cinemaEntities : DbContext
    {
        public cinemaEntities()
            : base("name=cinemaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Description> Description { get; set; }
        public DbSet<DescriptionGenres> DescriptionGenres { get; set; }
        public DbSet<PerformanceDays> PerformanceDays { get; set; }
        public DbSet<Shows> Shows { get; set; }
    }
}
