//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shows
    {
        public Shows()
        {
            this.PerformanceDays = new HashSet<PerformanceDays>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public int DescriptionId { get; set; }
        public string CinemaHollHome { get; set; }
    
        public virtual Description Description { get; set; }
        public virtual ICollection<PerformanceDays> PerformanceDays { get; set; }
    }
}
